--- #YAML:1.0
distribution_type:     module
name:                  DBD-Wire10
license:               perl
version:               1.03
build_requires:
	Test:               0.0
requires:
	DBI:                0.0
	Net::Wire10:        1.03
meta-spec:
	url:                http://module-build.sourceforge.net/META-spec-v1.4.html
	version:            1.4
